version: '3'

services:
  music-bot:
    container_name: music-bot
    build: ./
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: 'postgres:12-alpine'
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres